# Generated by Django 5.2.1 on 2025-07-02 08:47

import django.db.models.deletion
import ecoles.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('niveau', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CycleEtude_createby', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CycleEtude_updateby', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Cylce',
                'verbose_name_plural': 'CYCLES',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Langue_createby', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Langue_updateby', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'LANGUES',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, verbose_name="Description de l'ecole")),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ecoles.utils.generic_upload_to, verbose_name="Limage de l'ecole")),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('email_contact', models.EmailField(max_length=100)),
                ('telephone_contact', models.CharField(max_length=50)),
                ('site_web', models.URLField(blank=True)),
                ('map_link', models.URLField(blank=True)),
                ('nom_directeur', models.CharField(blank=True, max_length=255)),
                ('email_directeur', models.EmailField(blank=True, max_length=254)),
                ('telephone_directeur', models.CharField(blank=True, max_length=50)),
                ('theme_color', models.CharField(default='#000', max_length=7)),
                ('nombre_max_classes', models.IntegerField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date creation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Date Modification')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ecole_createby', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('cycle', models.ManyToManyField(blank=True, related_name='ecoles', to='ecoles.cycleetude')),
                ('update_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ecole_updateby', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
                ('langue_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles_principales', to='ecoles.langue', verbose_name='Langue principale')),
                ('langues', models.ManyToManyField(blank=True, related_name='ecoles', to='ecoles.langue', verbose_name='Langues disponibles')),
            ],
            options={
                'verbose_name': 'Ecole',
                'verbose_name_plural': 'ECOLES',
                'ordering': ['-created_at'],
            },
        ),
    ]
