# Generated by Django 5.2.7 on 2025-10-19 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du pays (ex: Congo-Kinshasa)', max_length=100, unique=True)),
                ('prefix', models.CharField(help_text='Préfixe téléphonique international (ex: 243)', max_length=5, unique=True)),
                ('corps', models.CharField(help_text='Optionnel, reste du numéro après le préfixe (ex: 817928892 pour la RDC)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le préfixe est actif pour la validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant créé ce préfixe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryprefix_created', to=settings.AUTH_USER_MODEL)),
                ('update_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant modifié ce préfixe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryprefix_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country Prefix',
                'verbose_name_plural': 'Country Prefixes',
                'ordering': ['name'],
            },
        ),
    ]
