# Generated by Django 5.2.7 on 2025-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0002_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom complet du pays', max_length=100, verbose_name='Nom du pays')),
                ('code', models.CharField(help_text='Code ISO du pays (ex: FRA, USA)', max_length=3, unique=True, verbose_name='Code pays')),
                ('prefix', models.CharField(help_text='Préfixe téléphonique international (ex: 243)', max_length=5, unique=True, verbose_name='Préfixe téléphonique international')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le pays est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
    ]
