# Generated by Django 5.2.7 on 2025-10-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom complet de la langue (ex: Français, English)', max_length=100, unique=True, verbose_name='Nom de la langue')),
                ('code', models.CharField(help_text='Code de la langue (ex: fr, en)', max_length=10, unique=True, verbose_name='Code de la langue')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la langue est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['name'],
            },
        ),
    ]
