# Generated by Django 5.2.7 on 2025-11-10 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0004_language'),
        ('app_profile', '0009_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom unique de la permission (ex: app_profile.view_profile)', max_length=200, unique=True, verbose_name='Permission Name')),
                ('codename', models.CharField(help_text='Code unique de la permission (ex: view_profile)', max_length=200, unique=True, verbose_name='Code Name')),
                ('resource', models.CharField(choices=[('app_profile', 'Profile Management'), ('finance_app', 'Finance Management'), ('organisation_app', 'Organization Management'), ('app_config', 'Configuration')], help_text='Ressource concernée par cette permission', max_length=50, verbose_name='Resource')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('manage', 'Manage')], help_text='Action autorisée par cette permission', max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, help_text='Description de la permission', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la permission est active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['resource', 'action', 'name'],
                'indexes': [models.Index(fields=['resource', 'action'], name='app_config__resourc_c88eea_idx'), models.Index(fields=['codename'], name='app_config__codenam_1992f7_idx')],
                'unique_together': {('resource', 'action', 'codename')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du rôle (ex: Admin, User, Manager)', max_length=100, unique=True, verbose_name='Role Name')),
                ('codename', models.CharField(help_text='Code unique du rôle (ex: admin, user)', max_length=100, unique=True, verbose_name='Code Name')),
                ('role_type', models.CharField(choices=[('system', 'System Role'), ('custom', 'Custom Role')], default='custom', help_text='Type de rôle (système ou personnalisé)', max_length=20, verbose_name='Role Type')),
                ('description', models.TextField(blank=True, help_text='Description du rôle', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le rôle est actif', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions associées à ce rôle', related_name='roles', to='app_config.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=True, help_text='True pour accorder, False pour refuser explicitement', verbose_name='Granted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('granted_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a accordé cette permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('permission', models.ForeignKey(help_text='Permission assignée', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='app_config.permission', verbose_name='Permission')),
                ('profile', models.ForeignKey(help_text='Profil utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='app_profile.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le rôle est actif pour cet utilisateur', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a assigné ce rôle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('profile', models.ForeignKey(help_text='Profil utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='app_profile.profile', verbose_name='Profile')),
                ('role', models.ForeignKey(help_text='Rôle assigné', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='app_config.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['codename'], name='app_config__codenam_066eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['profile', 'permission'], name='app_config__profile_8495d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together={('profile', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['profile', 'role'], name='app_config__profile_f3fba0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('profile', 'role')},
        ),
    ]
