# Generated by Django 5.2.7 on 2025-11-13 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0005_permission_role_userpermission_userrole_and_more'),
        ('app_profile', '0010_documentverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userpermission',
            name='app_config__profile_8495d3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userpermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='permissions',
            field=models.ManyToManyField(help_text='Permissions assignées', related_name='user_permissions', to='app_config.permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a accordé ces permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Granted By'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['profile', 'granted'], name='app_config__profile_ec9e90_idx'),
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='permission',
        ),
    ]
