# Generated by Django 5.2.7 on 2025-11-13 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0006_remove_userpermission_app_config__profile_8495d3_idx_and_more'),
        ('app_profile', '0010_documentverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si cette assignation de permissions est active', verbose_name='Is Active'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['profile', 'is_active'], name='app_config__profile_21502b_idx'),
        ),
    ]
