# Generated by Django 5.2.7 on 2025-11-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0007_userpermission_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('app_profile', 'Profile Application'), ('finance_app', 'Finance Application'), ('organisation_app', 'Organization Application'), ('app_config', 'Configuration Application')], help_text='Ressource concernée par cette permission', max_length=50, verbose_name='Resource'),
        ),
    ]
