# Generated by Django 5.2.7 on 2025-11-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0008_alter_permission_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='Code ISO du pays (ex: FRA, USA)', max_length=3, verbose_name='Code pays'),
        ),
        migrations.AlterField(
            model_name='country',
            name='prefix',
            field=models.CharField(help_text='Préfixe téléphonique international (ex: 243)', max_length=5, verbose_name='Préfixe téléphonique international'),
        ),
        migrations.AlterField(
            model_name='countryprefix',
            name='name',
            field=models.CharField(help_text='Nom du pays (ex: Congo-Kinshasa)', max_length=100),
        ),
        migrations.AlterField(
            model_name='countryprefix',
            name='prefix',
            field=models.CharField(help_text='Préfixe téléphonique international (ex: 243)', max_length=5),
        ),
    ]
