# Generated by Django 5.2.7 on 2025-11-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0009_alter_country_code_alter_country_prefix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(help_text='Code unique de la permission (ex: view_profile)', verbose_name='Code Name'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(help_text='Nom unique de la permission (ex: app_profile.view_profile)', max_length=200, verbose_name='Permission Name'),
        ),
    ]
