# Generated by Django 5.2.7 on 2025-10-18 10:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom complet du pays', max_length=100, verbose_name='Nom du pays')),
                ('code', models.CharField(help_text='Code ISO du pays (ex: FRA, USA)', max_length=3, unique=True, verbose_name='Code pays')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nom et prénom du titulaire du compte', max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone (optionnel)', max_length=20, null=True, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le profil est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('country', models.ForeignKey(help_text='Pays de résidence du titulaire', on_delete=django.db.models.deletion.PROTECT, to='app_profile.country', verbose_name='Pays')),
                ('user', models.OneToOneField(help_text='Utilisateur Django associé à ce profil', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Parent',
                'verbose_name_plural': 'Profils Parents',
                'ordering': ['full_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Nom et prénom de l'enfant", max_length=200, verbose_name='Nom complet')),
                ('age', models.PositiveIntegerField(blank=True, help_text="Âge de l'enfant (optionnel)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Âge')),
                ('relationship', models.CharField(choices=[('son', 'Fils'), ('daughter', 'Fille'), ('ward', 'Pupille'), ('other', 'Autre')], default='other', help_text='Relation avec le parent', max_length=20, verbose_name='Relation')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le profil enfant est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('parent', models.ForeignKey(help_text='Profil parent responsable', on_delete=django.db.models.deletion.CASCADE, to='app_profile.parentprofile', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Profil Enfant',
                'verbose_name_plural': 'Profils Enfants',
                'ordering': ['parent', 'full_name'],
                'unique_together': {('parent', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'organisation", max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text="Description de l'organisation (optionnel)", null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'organisation est active", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('members', models.ManyToManyField(blank=True, help_text='Enfants membres de cette organisation', to='app_profile.childprofile', verbose_name='Membres')),
                ('owner', models.ForeignKey(help_text="Profil parent propriétaire de l'organisation", on_delete=django.db.models.deletion.CASCADE, to='app_profile.parentprofile', verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name', '-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
