# Generated by Django 5.2.7 on 2025-10-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date de naissance du titulaire (optionnel)', null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='firstname',
            field=models.CharField(blank=True, help_text='Prénom du titulaire du compte', max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indique si le profil a été vérifié', verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='name',
            field=models.CharField(blank=True, help_text='Nom de famille du titulaire du compte', max_length=100, null=True, verbose_name='Nom de famille'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Pays d'origine du titulaire", null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.country', verbose_name='Pays'),
        ),
    ]
