# Generated by Django 5.2.7 on 2025-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_parentprofile_birth_date_parentprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Féminin'), ('other', 'Autre')], help_text='Genre du titulaire (optionnel)', max_length=10, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='id_card_number',
            field=models.CharField(blank=True, help_text="Numéro de la pièce d'identité (optionnel)", max_length=50, null=True, verbose_name="Numéro de pièce d'identité"),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='pincode',
            field=models.CharField(blank=True, help_text='Code PIN personnel (optionnel)', max_length=20, null=True, verbose_name='Code PIN'),
        ),
    ]
