# Generated by Django 5.2.7 on 2025-10-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_data_to_profile(apps, schema_editor):
    """
    Migre les données existantes de ParentProfile vers le nouveau modèle Profile.
    """
    ParentProfile = apps.get_model('app_profile', 'ParentProfile')
    Profile = apps.get_model('app_profile', 'Profile')
    User = apps.get_model('auth', 'User')
    
    # Créer un Profile pour chaque ParentProfile existant
    for parent_profile in ParentProfile.objects.all():
        # Créer le Profile correspondant
        profile = Profile.objects.create(
            user=parent_profile.user,
            full_name=parent_profile.full_name,
            firstname=parent_profile.firstname,
            name=parent_profile.name,
            birth_date=parent_profile.birth_date,
            id_card_number=parent_profile.id_card_number,
            pincode=parent_profile.pincode,
            gender=parent_profile.gender,
            country=parent_profile.country,
            phone=parent_profile.phone,
            is_verified=parent_profile.is_verified,
            is_active=parent_profile.is_active,
            created_at=parent_profile.created_at,
            updated_at=parent_profile.updated_at,
        )
        
        # Mettre à jour le ParentProfile pour pointer vers le nouveau Profile
        parent_profile.profile = profile
        parent_profile.save()


def reverse_migrate_data(apps, schema_editor):
    """
    Opération inverse : supprime les Profile et restaure les données dans ParentProfile.
    """
    # Cette fonction sera appelée si on fait un rollback
    # Pour l'instant, on ne l'implémente pas car c'est complexe
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_parentprofile_gender_parentprofile_id_card_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Créer le modèle Profile d'abord
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Nom et prénom du titulaire du compte', max_length=200, verbose_name='Nom complet')),
                ('firstname', models.CharField(blank=True, help_text='Prénom du titulaire du compte', max_length=100, null=True, verbose_name='Prénom')),
                ('name', models.CharField(blank=True, help_text='Nom de famille du titulaire du compte', max_length=100, null=True, verbose_name='Nom de famille')),
                ('birth_date', models.DateField(blank=True, help_text='Date de naissance du titulaire (optionnel)', null=True, verbose_name='Date de naissance')),
                ('id_card_number', models.CharField(blank=True, help_text="Numéro de la pièce d'identité (optionnel)", max_length=50, null=True, verbose_name="Numéro de pièce d'identité")),
                ('pincode', models.CharField(blank=True, help_text='Code PIN personnel (optionnel)', max_length=20, null=True, verbose_name='Code PIN')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Féminin'), ('other', 'Autre')], help_text='Genre du titulaire (optionnel)', max_length=10, null=True, verbose_name='Genre')),
                ('phone', models.CharField(blank=True, help_text='Numéro de téléphone (optionnel)', max_length=20, null=True, verbose_name='Téléphone')),
                ('is_verified', models.BooleanField(default=False, help_text='Indique si le profil a été vérifié', verbose_name='Vérifié')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le profil est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('country', models.ForeignKey(blank=True, help_text="Pays d'origine du titulaire", null=True, on_delete=django.db.models.deletion.PROTECT, to='app_profile.country', verbose_name='Pays')),
                ('user', models.OneToOneField(help_text='Utilisateur Django associé à ce profil', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['created_at'],
                'unique_together': {('phone',)},
            },
        ),
        
        # Ajouter le champ profile à ParentProfile (nullable d'abord)
        migrations.AddField(
            model_name='parentprofile',
            name='profile',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='app_profile.profile', verbose_name='Profile'),
        ),
        
        # Ajouter le champ profile à ChildProfile (nullable d'abord)
        migrations.AddField(
            model_name='childprofile',
            name='profile',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to='app_profile.profile', verbose_name='Profile'),
        ),
        
        # Migrer les données
        migrations.RunPython(migrate_data_to_profile, reverse_migrate_data),
        
        # Rendre les champs obligatoires après migration
        migrations.AlterField(
            model_name='parentprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='app_profile.profile', verbose_name='Profile'),
        ),
        
        migrations.AlterField(
            model_name='childprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to='app_profile.profile', verbose_name='Profile'),
        ),
        
        # Supprimer d'abord les contraintes d'unicité pour éviter les erreurs SQLite
        migrations.AlterUniqueTogether(
            name='childprofile',
            unique_together=set(),
        ),
        
        # Supprimer les anciens champs de ParentProfile
        migrations.RemoveField(
            model_name='parentprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='id_card_number',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='user',
        ),
        
        # Supprimer les anciens champs de ChildProfile
        migrations.RemoveField(
            model_name='childprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='full_name',
        ),
        
        # Mettre à jour les options des modèles
        migrations.AlterModelOptions(
            name='childprofile',
            options={'ordering': ['parent', 'profile__full_name'], 'verbose_name': 'Profil Enfant', 'verbose_name_plural': 'Profils Enfants'},
        ),
        migrations.AlterModelOptions(
            name='parentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Profil Parent', 'verbose_name_plural': 'Profils Parents'},
        ),
        
        # Mettre à jour les contraintes d'unicité
        migrations.AlterUniqueTogether(
            name='childprofile',
            unique_together={('parent', 'profile')},
        ),
    ]