# Generated by Django 5.2.7 on 2025-10-22 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0003_country'),
        ('app_profile', '0004_migrate_to_profile_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Pays d'origine du titulaire", null=True, on_delete=django.db.models.deletion.PROTECT, to='app_config.country', verbose_name='Pays'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
