# Generated by Django 5.2.7 on 2025-11-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_add_reference_to_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='app_profile_referen_idx',
        ),
    ]
