# Generated by Django 5.2.7 on 2025-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0007_remove_profile_app_profile_referen_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_wallets',
            field=models.PositiveIntegerField(default=5, help_text='Nombre maximum de wallets que cet utilisateur peut créer (0 = illimité)', verbose_name='Nombre maximum de wallets'),
        ),
    ]
