# Generated by Django 5.2.7 on 2025-11-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0008_add_max_wallets_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur (max 2 Mo)", null=True, upload_to='profiles/photos/', verbose_name='Photo de profil'),
        ),
    ]
