# Generated by Django 5.2.7 on 2025-11-13 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0009_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('driver_license', 'Permis de conduire'), ('other', 'Autre document')], help_text="Type de document d'identité", max_length=50, verbose_name='Type de document')),
                ('document_front', models.ImageField(help_text='Photo du recto du document (max 5 Mo)', upload_to='verifications/documents/', verbose_name='Recto du document')),
                ('document_back', models.ImageField(blank=True, help_text='Photo du verso du document (max 5 Mo, optionnel)', null=True, upload_to='verifications/documents/', verbose_name='Verso du document')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('under_review', 'En cours de vérification'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', help_text='Statut de la vérification', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes internes pour la vérification', null=True, verbose_name='Notes administrateur')),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet si la vérification est refusée', null=True, verbose_name='Raison du rejet')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date à laquelle le document a été vérifié', null=True, verbose_name='Date de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('profile', models.ForeignKey(help_text='Profil à vérifier', on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='app_profile.profile', verbose_name='Profil')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Administrateur qui a vérifié le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par')),
            ],
            options={
                'verbose_name': 'Vérification de document',
                'verbose_name_plural': 'Vérifications de documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'status'], name='app_profile_profile_ea1e47_idx'), models.Index(fields=['status', 'created_at'], name='app_profile_status_ef9cd8_idx')],
            },
        ),
    ]
