# Generated by Django 5.2.7 on 2025-11-13 22:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0010_documentverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('pt', 'Português')], default='fr', help_text="Langue préférée de l'interface", max_length=10, verbose_name='Langue')),
                ('timezone', models.CharField(default='UTC', help_text='Timezone préférée (ex: Africa/Kinshasa, UTC)', max_length=100, verbose_name='Timezone')),
                ('email_notifications', models.BooleanField(default=True, help_text='Recevoir des notifications par email', verbose_name='Notifications email')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Recevoir des notifications par SMS', verbose_name='Notifications SMS')),
                ('push_notifications', models.BooleanField(default=True, help_text='Recevoir des notifications push', verbose_name='Notifications push')),
                ('transaction_notifications', models.BooleanField(default=True, help_text='Recevoir des notifications pour les transactions', verbose_name='Notifications de transactions')),
                ('security_notifications', models.BooleanField(default=True, help_text='Recevoir des notifications de sécurité', verbose_name='Notifications de sécurité')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text="Thème d'affichage préféré", max_length=10, verbose_name='Thème')),
                ('items_per_page', models.PositiveIntegerField(default=20, help_text="Nombre d'éléments à afficher par page", validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Éléments par page')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends only')], default='private', help_text='Qui peut voir votre profil', max_length=20, verbose_name='Visibilité du profil')),
                ('show_email', models.BooleanField(default=False, help_text="Afficher l'email dans le profil public", verbose_name="Afficher l'email")),
                ('show_phone', models.BooleanField(default=False, help_text='Afficher le numéro de téléphone dans le profil public', verbose_name='Afficher le téléphone')),
                ('allow_search', models.BooleanField(default=True, help_text='Permettre aux autres utilisateurs de vous trouver', verbose_name='Autoriser la recherche')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé à')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié à')),
                ('profile', models.OneToOneField(help_text='Profil utilisateur', on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='app_profile.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="Nom d'utilisateur utilisé pour la connexion", max_length=150, verbose_name="Nom d'utilisateur")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP de la connexion', null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur/appareil', null=True, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, help_text="Nom identifiant l'appareil", max_length=200, null=True, verbose_name="Nom de l'appareil")),
                ('location', models.CharField(blank=True, help_text='Localisation estimée', max_length=200, null=True, verbose_name='Localisation')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec'), ('blocked', 'Bloqué')], default='success', help_text='Statut de la tentative de connexion', max_length=20, verbose_name='Statut')),
                ('failure_reason', models.CharField(blank=True, help_text="Raison de l'échec de connexion (si applicable)", max_length=200, null=True, verbose_name="Raison de l'échec")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la tentative', verbose_name='Date')),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur concerné (null si échec)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historiques de connexion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='app_profile_user_id_52cf55_idx'), models.Index(fields=['username', 'created_at'], name='app_profile_usernam_11fb01_idx'), models.Index(fields=['ip_address', 'created_at'], name='app_profile_ip_addr_142c88_idx'), models.Index(fields=['status'], name='app_profile_status_cee314_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(help_text="Nom identifiant l'appareil", max_length=200, verbose_name="Nom de l'appareil")),
                ('device_fingerprint', models.CharField(help_text="Empreinte unique de l'appareil (hash)", max_length=255, unique=True, verbose_name="Empreinte de l'appareil")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP lors de l'enregistrement", null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text="User agent de l'appareil", null=True, verbose_name='User Agent')),
                ('location', models.CharField(blank=True, help_text="Localisation lors de l'enregistrement", max_length=200, null=True, verbose_name='Localisation')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'appareil est toujours de confiance", verbose_name='Actif')),
                ('last_used', models.DateTimeField(auto_now=True, help_text="Dernière fois que l'appareil a été utilisé", verbose_name='Dernière utilisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date d'enregistrement de l'appareil", verbose_name='Créé à')),
                ('user', models.ForeignKey(help_text="Utilisateur propriétaire de l'appareil", on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Appareil de confiance',
                'verbose_name_plural': 'Appareils de confiance',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='app_profile_user_id_e9a8d4_idx'), models.Index(fields=['device_fingerprint'], name='app_profile_device__93c603_idx')],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(help_text='Clé unique de la session Django', max_length=40, unique=True, verbose_name='Clé de session')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Adresse IP de la connexion', null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur/appareil', null=True, verbose_name='User Agent')),
                ('device_name', models.CharField(blank=True, help_text="Nom identifiant l'appareil (ex: Chrome on Windows)", max_length=200, null=True, verbose_name="Nom de l'appareil")),
                ('location', models.CharField(blank=True, help_text='Localisation estimée (ville, pays)', max_length=200, null=True, verbose_name='Localisation')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la session est active', verbose_name='Actif')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Dernière activité sur cette session', verbose_name='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la session', verbose_name='Créé à')),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire de la session', on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateur',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='app_profile_user_id_210c28_idx'), models.Index(fields=['session_key'], name='app_profile_session_d6c513_idx')],
            },
        ),
    ]
