# Generated by Django 5.2.7 on 2025-11-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0011_userpreferences_loginhistory_trusteddevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentverification',
            name='address',
            field=models.TextField(default=1, help_text="Adresse complète de l'utilisateur", verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentverification',
            name='selfie_photo',
            field=models.ImageField(default=1, help_text='Photo de soi-même pour la vérification (max 5 Mo)', upload_to='verifications/selfies/', verbose_name='Photo de soi-même'),
            preserve_default=False,
        ),
    ]
