# Generated by Django 5.2.4 on 2025-11-28 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0012_documentverification_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='members',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Élève'), ('teacher', 'Enseignant'), ('parent', 'Parent'), ('admin', 'Administrateur'), ('staff', 'Personnel')], help_text='Rôle principal du profil', max_length=20, null=True, verbose_name='Rôle'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_number', models.CharField(blank=True, help_text="Numéro unique d'identification du parent", max_length=50, null=True, unique=True, verbose_name='Numéro de parent')),
                ('relationship_type', models.CharField(blank=True, help_text='Type de relation (père, mère, tuteur, etc.)', max_length=50, null=True, verbose_name='Type de relation')),
                ('occupation', models.CharField(blank=True, help_text='Profession du parent', max_length=200, null=True, verbose_name='Profession')),
                ('emergency_contact', models.BooleanField(default=False, help_text="Indique si ce parent est un contact d'urgence", verbose_name="Contact d'urgence")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le parent est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé ce parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('profile', models.OneToOneField(help_text='Profil associé à ce parent', on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app_profile.profile', verbose_name='Profil')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié ce parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(blank=True, help_text="Numéro unique d'identification de l'élève", max_length=50, null=True, unique=True, verbose_name="Numéro d'élève")),
                ('enrollment_date', models.DateField(blank=True, help_text="Date d'inscription de l'élève", null=True, verbose_name="Date d'inscription")),
                ('class_level', models.CharField(blank=True, help_text="Niveau ou classe de l'élève", max_length=50, null=True, verbose_name='Niveau de classe')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'élève est actif", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cet élève', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('profile', models.OneToOneField(help_text='Profil associé à cet élève', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='app_profile.profile', verbose_name='Profil')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié cet élève', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_number', models.CharField(blank=True, help_text="Numéro unique d'identification de l'enseignant", max_length=50, null=True, unique=True, verbose_name="Numéro d'enseignant")),
                ('hire_date', models.DateField(blank=True, help_text="Date d'embauche de l'enseignant", null=True, verbose_name="Date d'embauche")),
                ('specialization', models.CharField(blank=True, help_text="Domaine de spécialisation de l'enseignant", max_length=200, null=True, verbose_name='Spécialisation')),
                ('department', models.CharField(blank=True, help_text="Département de l'enseignant", max_length=100, null=True, verbose_name='Département')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'enseignant est actif", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cet enseignant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('profile', models.OneToOneField(help_text='Profil associé à cet enseignant', on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='app_profile.profile', verbose_name='Profil')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié cet enseignant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChildProfile',
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['parent_number'], name='app_profile_parent__3c2792_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['is_active', 'created_at'], name='app_profile_is_acti_39cbb9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='app_profile_student_220c52_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active', 'created_at'], name='app_profile_is_acti_9bd259_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_number'], name='app_profile_teacher_1b47ac_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_active', 'created_at'], name='app_profile_is_acti_d0aad8_idx'),
        ),
    ]
