# Generated by Django 5.2.7 on 2025-12-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academic', '0001_initial'),
        ('app_profile', '0013_remove_organisation_members_profile_role_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text="Année scolaire de l'élève", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app_academic.academicyear', verbose_name='Année scolaire'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_section',
            field=models.ForeignKey(blank=True, help_text="Classe de l'élève", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='app_academic.class', verbose_name='Classe'),
        ),
    ]
