# Generated by Django 5.2.7 on 2025-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academic', '0001_initial'),
        ('app_profile', '0014_student_academic_year_student_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text="Classes où l'enseignant enseigne", related_name='teachers', to='app_academic.class', verbose_name='Classes enseignées'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text="Matières que l'enseignant enseigne", related_name='teachers', to='app_academic.subject', verbose_name='Matières enseignées'),
        ),
    ]
