# Generated by Django 5.2.7 on 2025-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0015_teacher_classes_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='children',
            field=models.ManyToManyField(blank=True, help_text='Enfants de ce parent', related_name='parents', to='app_profile.student', verbose_name='Enfants'),
        ),
    ]
