# Generated by Django 5.2.7 on 2025-12-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_academic', '0001_initial'),
        ('app_profile', '0016_parent_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text="Date de début de l'absence", verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, help_text="Date de fin de l'absence (si absence sur plusieurs jours)", null=True, verbose_name='Date de fin')),
                ('reason', models.TextField(help_text="Motif de l'absence", verbose_name='Motif')),
                ('is_justified', models.BooleanField(default=False, help_text="Indique si l'absence est justifiée", verbose_name='Justifiée')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'absence est active", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('justified_by', models.ForeignKey(blank=True, help_text="Enseignant qui a justifié l'absence", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justified_absences', to='app_profile.teacher', verbose_name='Justifiée par')),
                ('student', models.ForeignKey(help_text='Élève concerné', on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='app_profile.student', verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-start_date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date de la présence', verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard'), ('excused', 'Excusé')], default='present', help_text='Statut de présence', max_length=20, verbose_name='Statut')),
                ('time_in', models.TimeField(blank=True, help_text="Heure d'arrivée de l'élève", null=True, verbose_name="Heure d'arrivée")),
                ('time_out', models.TimeField(blank=True, help_text="Heure de départ de l'élève", null=True, verbose_name='Heure de départ')),
                ('notes', models.TextField(blank=True, help_text='Notes supplémentaires', null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la présence est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('class_section', models.ForeignKey(help_text='Classe concernée', on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='app_academic.class', verbose_name='Classe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('student', models.ForeignKey(help_text='Élève concerné', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app_profile.student', verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la règle', max_length=100, unique=True, verbose_name='Nom')),
                ('max_absences', models.IntegerField(default=5, help_text="Nombre maximum d'absences autorisées", verbose_name="Nombre maximum d'absences")),
                ('alert_threshold', models.IntegerField(default=3, help_text="Nombre d'absences déclenchant une alerte", verbose_name="Seuil d'alerte")),
                ('period_days', models.IntegerField(default=30, help_text='Période en jours pour le calcul des absences', verbose_name='Période (jours)')),
                ('description', models.TextField(blank=True, help_text='Description de la règle', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la règle est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_rules_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Règle de présence',
                'verbose_name_plural': 'Règles de présence',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Excuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Document justificatif (PDF, image)', upload_to='excuses/documents/', verbose_name='Document')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', help_text='Statut du justificatif', max_length=20, verbose_name='Statut')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date à laquelle le justificatif a été examiné', null=True, verbose_name="Date d'examen")),
                ('notes', models.TextField(blank=True, help_text='Notes sur le justificatif', null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le justificatif est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('absence', models.OneToOneField(help_text='Absence concernée', on_delete=django.db.models.deletion.CASCADE, related_name='excuse', to='app_attendance.absence', verbose_name='Absence')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excuses_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Enseignant qui a examiné le justificatif', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_excuses', to='app_profile.teacher', verbose_name='Examiné par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excuses_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['student', 'start_date'], name='app_attenda_student_e720d1_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['is_justified', 'start_date'], name='app_attenda_is_just_23e7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='app_attenda_student_42b8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_section', 'date'], name='app_attenda_class_s_1bb154_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'date'], name='app_attenda_status_a0aa36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'class_section', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['name'], name='app_attenda_name_94b1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerule',
            index=models.Index(fields=['is_active'], name='app_attenda_is_acti_2cd8e9_idx'),
        ),
        migrations.AddIndex(
            model_name='excuse',
            index=models.Index(fields=['status', 'created_at'], name='app_attenda_status_5b7421_idx'),
        ),
        migrations.AddIndex(
            model_name='excuse',
            index=models.Index(fields=['absence'], name='app_attenda_absence_0c6227_idx'),
        ),
    ]
