# Generated by Django 5.2.4 on 2025-12-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excuse',
            name='document',
            field=models.FileField(blank=True, help_text='Document justificatif (PDF, image)', null=True, upload_to='excuses/documents/', verbose_name='Document'),
        ),
    ]
