# Generated by Django 5.2.7 on 2025-12-06 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_academic', '0001_initial'),
        ('app_profile', '0016_parent_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie (ex: Contrôle continu, Examen)', max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code unique de la catégorie', max_length=20, unique=True, verbose_name='Code')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Poids de la catégorie pour le calcul de la moyenne', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Poids')),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la catégorie est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_categories_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Catégorie d'évaluation",
                'verbose_name_plural': "Catégories d'évaluation",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'évaluation (ex: Contrôle de Mathématiques)", max_length=200, verbose_name='Nom')),
                ('date', models.DateField(help_text="Date de l'évaluation", verbose_name='Date')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text="Coefficient de l'évaluation", max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Coefficient')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Note maximale possible', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Note maximale')),
                ('description', models.TextField(blank=True, help_text="Description de l'évaluation", null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'évaluation est active", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('academic_year', models.ForeignKey(help_text="Année scolaire de l'évaluation", on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='app_academic.academicyear', verbose_name='Année scolaire')),
                ('class_section', models.ForeignKey(help_text='Classe concernée', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='app_academic.class', verbose_name='Classe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('subject', models.ForeignKey(help_text='Matière concernée', on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='app_academic.subject', verbose_name='Matière')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('category', models.ForeignKey(help_text="Catégorie de l'évaluation", on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='app_grades.gradecategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date', 'subject', 'class_section'],
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du barème (ex: 0-20, A-F)', max_length=50, unique=True, verbose_name='Nom')),
                ('min_score', models.DecimalField(decimal_places=2, help_text='Note minimale du barème', max_digits=5, verbose_name='Note minimale')),
                ('max_score', models.DecimalField(decimal_places=2, help_text='Note maximale du barème', max_digits=5, verbose_name='Note maximale')),
                ('passing_score', models.DecimalField(decimal_places=2, help_text='Note minimale pour réussir', max_digits=5, verbose_name='Note de passage')),
                ('description', models.TextField(blank=True, help_text='Description du barème', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le barème est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scales_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scales_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Barème de notation',
                'verbose_name_plural': 'Barèmes de notation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Période (ex: Trimestre 1, Semestre 1)', max_length=50, verbose_name='Trimestre/Semestre')),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, help_text="Moyenne générale de l'élève", max_digits=5, null=True, verbose_name='Moyenne générale')),
                ('rank', models.IntegerField(blank=True, help_text="Classement de l'élève dans sa classe", null=True, verbose_name='Classement')),
                ('total_students', models.IntegerField(blank=True, help_text="Nombre total d'élèves dans la classe", null=True, verbose_name="Nombre total d'élèves")),
                ('comments', models.TextField(blank=True, help_text='Commentaires généraux sur le bulletin', null=True, verbose_name='Commentaires')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le bulletin est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('academic_year', models.ForeignKey(help_text='Année scolaire du bulletin', on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='app_academic.academicyear', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('student', models.ForeignKey(help_text='Élève concerné', on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='app_profile.student', verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-academic_year', 'student', '-term'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text="Note obtenue par l'élève", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note')),
                ('comment', models.TextField(blank=True, help_text='Commentaire sur la note', null=True, verbose_name='Commentaire')),
                ('is_absent', models.BooleanField(default=False, help_text="Indique si l'élève était absent lors de l'évaluation", verbose_name='Absent')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la note est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('assessment', models.ForeignKey(help_text='Évaluation concernée', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='app_grades.assessment', verbose_name='Évaluation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grades_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('student', models.ForeignKey(help_text='Élève concerné', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='app_profile.student', verbose_name='Élève')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_grades_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Note d'élève",
                'verbose_name_plural': "Notes d'élèves",
                'ordering': ['-assessment__date', 'student'],
            },
        ),
        migrations.AddIndex(
            model_name='gradecategory',
            index=models.Index(fields=['code'], name='app_grades__code_dcee97_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecategory',
            index=models.Index(fields=['is_active'], name='app_grades__is_acti_c55435_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['subject', 'class_section', 'date'], name='app_grades__subject_35c479_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['academic_year', 'is_active'], name='app_grades__academi_f1da6a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['category', 'date'], name='app_grades__categor_7e706b_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['name'], name='app_grades__name_587a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['is_active'], name='app_grades__is_acti_ba29f8_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student', 'academic_year'], name='app_grades__student_ce4fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['academic_year', 'term'], name='app_grades__academi_a4678b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['student', 'assessment'], name='app_grades__student_ccc3ec_idx'),
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['assessment', 'is_active'], name='app_grades__assessm_7b535d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('student', 'assessment')},
        ),
    ]
