# Generated by Django 5.2.7 on 2025-12-06 21:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_profile', '0013_remove_organisation_members_profile_role_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'année scolaire (ex: 2024-2025)", max_length=50, unique=True, verbose_name='Nom')),
                ('start_date', models.DateField(help_text="Date de début de l'année scolaire", verbose_name='Date de début')),
                ('end_date', models.DateField(help_text="Date de fin de l'année scolaire", verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, help_text="Indique si c'est l'année scolaire actuelle", verbose_name='Année courante')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'année scolaire est active", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a créé cette année scolaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_years_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a modifié cette année scolaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_years_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la salle (ex: Salle 101, Laboratoire de Sciences)', max_length=100, unique=True, verbose_name='Nom')),
                ('capacity', models.IntegerField(help_text="Nombre maximum d'élèves que la salle peut accueillir", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('floor', models.IntegerField(blank=True, help_text="Numéro de l'étage (optionnel)", null=True, verbose_name='Étage')),
                ('equipment', models.TextField(blank=True, help_text='Liste des équipements disponibles dans la salle', null=True, verbose_name='Équipements')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la salle est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Salle de classe',
                'verbose_name_plural': 'Salles de classe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la classe (ex: 6ème A, 5ème B)', max_length=100, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code unique de la classe', max_length=50, unique=True, verbose_name='Code')),
                ('capacity', models.IntegerField(help_text="Nombre maximum d'élèves dans la classe", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la classe est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('academic_year', models.ForeignKey(help_text='Année scolaire de la classe', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='app_academic.academicyear', verbose_name='Année scolaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('teacher', models.ForeignKey(blank=True, help_text='Professeur principal de la classe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_classes', to='app_profile.teacher', verbose_name='Professeur principal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('classroom', models.ForeignKey(blank=True, help_text='Salle de classe principale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='app_academic.classroom', verbose_name='Salle de classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['academic_year', 'grade__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le cours est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('academic_year', models.ForeignKey(help_text='Année scolaire du cours', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='app_academic.academicyear', verbose_name='Année scolaire')),
                ('class_section', models.ForeignKey(help_text='Classe concernée', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='app_academic.class', verbose_name='Classe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('teacher', models.ForeignKey(help_text='Enseignant responsable du cours', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='app_profile.teacher', verbose_name='Enseignant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['academic_year', 'class_section', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du niveau (ex: CP, CE1, 6ème)', max_length=50, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code unique du niveau', max_length=20, unique=True, verbose_name='Code')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage du niveau", verbose_name='Ordre')),
                ('description', models.TextField(blank=True, help_text='Description du niveau', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le niveau est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.ForeignKey(help_text='Niveau scolaire de la classe', on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='app_academic.grade', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], help_text='Jour de la semaine (0=Lundi, 6=Dimanche)', verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(help_text='Heure de début du cours', verbose_name='Heure de début')),
                ('end_time', models.TimeField(help_text='Heure de fin du cours', verbose_name='Heure de fin')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si le créneau est actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('classroom', models.ForeignKey(blank=True, help_text='Salle de classe pour ce créneau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='app_academic.classroom', verbose_name='Salle')),
                ('course', models.ForeignKey(help_text='Cours concerné', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app_academic.course', verbose_name='Cours')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Emploi du temps',
                'verbose_name_plural': 'Emplois du temps',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la matière (ex: Mathématiques, Français)', max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='Code unique de la matière', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Description de la matière', null=True, verbose_name='Description')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Coefficient pour le calcul de la moyenne', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Coefficient')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si la matière est active', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='Matière enseignée', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='app_academic.subject', verbose_name='Matière'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_current', 'is_active'], name='app_academi_is_curr_0215ff_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['start_date', 'end_date'], name='app_academi_start_d_73b5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['name'], name='app_academi_name_e06816_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['is_active'], name='app_academi_is_acti_a5f008_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['code'], name='app_academi_code_2c2a3f_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['is_active', 'order'], name='app_academi_is_acti_42f45b_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['code'], name='app_academi_code_5ceb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year', 'is_active'], name='app_academi_academi_17ea2d_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['grade', 'academic_year'], name='app_academi_grade_i_043f5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('code', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['course', 'day_of_week'], name='app_academi_course__43a705_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day_of_week', 'start_time'], name='app_academi_day_of__678f02_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='app_academi_code_152bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['is_active'], name='app_academi_is_acti_72625c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['academic_year', 'is_active'], name='app_academi_academi_fd68b9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['class_section', 'subject'], name='app_academi_class_s_5560ec_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher', 'academic_year'], name='app_academi_teacher_a0fcb0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'class_section', 'teacher', 'academic_year')},
        ),
    ]
